In [1]:
import numpy as np

In [29]:
def find_inverse_matrix(a: np.ndarray, show_annotation : bool = False) -> np.ndarray:
    A = a.astype(float)
    
    if A.shape[0] != A.shape[1]:
        raise ValueError("Matrix a must be square")

    det_a = np.linalg.det(A)
    if abs(det_a) < 1e-13:
        raise ValueError("Determinant is zero — matrix is not invertable")
    
    P = np.array([[1 / A[0][0]]])
    if show_annotation:
            print(f"Step 1:")
            print(P)
    
    for i in range(1, len(A)):
        D = np.zeros((i+1, i+1))
        D[:i,:i] = P
        
        u = A[:i,i].reshape(-1,1)
        v = A[i,:i].reshape(1,-1) 
        an = A[i,i] - (v @ P @ u)[0,0]
        
        r = -(P @ u) / an
        q = -(v @ P) / an
        
        D[i,:i] = q
        D[:i,i] = r.flatten()
        D[i,i] = 1 / an
        
        D[:i,:i] = P + (P @ u @ v @ P) / an
        
        P = D
        if show_annotation:
            print(f"Step {i+1}:")
            print(P)
        
    return P


def border_method(a: np.ndarray, b:np.ndarray, show_annotation : bool = False) -> np.ndarray:
    if a.shape[0] != a.shape[1]:
        raise ValueError("Matrix a must be square")
    
    if a.shape[0] != b.shape[0]:
        raise ValueError("The dimensions of the two arrays must match")
    
    det_a = np.linalg.det(a)
    if abs(det_a) < 1e-13:
        raise ValueError("Determinant is zero — system has no unique solution")
    
    n = len(b)
    a = a.copy().astype(float)
    b = b.copy().astype(float)
    
    a_ = find_inverse_matrix(a, show_annotation=show_annotation)
    
    x = a_ @ b
    if show_annotation:
        print(x)
    
    return x

In [31]:
a = np.array([[1, 3, -2, 0, -2], 
              [3, 4, -5, 1, -3], 
              [-2, -5, 3, -2, 2], 
              [0, 1, -2, 5, 3], 
              [-2, -3, 2, 3, 4]])
b = np.array([0.5, 5.4, 5, 7.5, 3.3])

x = border_method(a, b, show_annotation=True)
print(x)

b_ = a @ x
max_error = np.max(np.abs(b - b_))
print("max error: ", max_error)

Step 1:
[[1.]]
Step 2:
[[-0.8  0.6]
 [ 0.6 -0.2]]
Step 3:
[[-3.25  0.25 -1.75]
 [ 0.25 -0.25 -0.25]
 [-1.75 -0.25 -1.25]]
Step 4:
[[-1.72972973  0.35135135 -0.83783784 -0.40540541]
 [ 0.35135135 -0.24324324 -0.18918919 -0.02702703]
 [-0.83783784 -0.18918919 -0.7027027  -0.24324324]
 [-0.40540541 -0.02702703 -0.24324324  0.10810811]]
Step 5:
[[-2.08  0.04 -0.76  0.12 -0.72]
 [ 0.04 -0.52 -0.12  0.44 -0.64]
 [-0.76 -0.12 -0.72 -0.36  0.16]
 [ 0.12  0.44 -0.36 -0.68  1.08]
 [-0.72 -0.64  0.16  1.08 -1.48]]
[-6.1 -2.2 -6.8 -0.9  0.2]
[-6.1 -2.2 -6.8 -0.9  0.2]
max error:  4.884981308350689e-15


In [33]:
def return_max_error(a, b):
    x = border_method(a, b)
    b_ = a @ x
    max_error = np.max(np.abs(b - b_))
    return max_error


a2 = np.array([[4, 2],
               [2, 3]])
b2 = np.array([6, 8])

a3 = np.array([[6, 2, 1],
               [2, 5, 2],
               [1, 2, 4]])
b3 = np.array([9, 10, 7])

a4 = np.array([[10, 2, 3, 1],
               [2, 8, 1, 0],
               [3, 1, 9, 4],
               [1, 0, 4, 7]])
b4 = np.array([12, 9, 11, 8])

a5 = np.array([[9, 1, 2, 3, 1],
               [1, 7, 1, 2, 0],
               [2, 1, 8, 1, 2],
               [3, 2, 1, 10, 3],
               [1, 0, 2, 3, 6]])
b5 = np.array([17, 13, 15, 18, 10])

a6 = np.array([[12, 3, 2, 1, 0, 2],
               [3, 9, 1, 0, 2, 1],
               [2, 1, 11, 4, 1, 2],
               [1, 0, 4, 10, 2, 3],
               [0, 2, 1, 2, 8, 1],
               [2, 1, 2, 3, 1, 9]])
b6 = np.array([15, 12, 18, 14, 10, 16])

systems = [
    (a2, b2),
    (a3, b3),
    (a4, b4),
    (a5, b5),
    (a6, b6)
]

for n in [8, 12, 16, 20, 40, 60, 80, 100, 200, 400, 600, 800]:
    A = np.random.randn(n, n)
    x_true = np.ones(n)
    b = A @ x_true
    systems.append((A, b))

for a, b in systems:
    err = return_max_error(a, b)
    print(f"{a.shape[0]}x{a.shape[0]} max error = {err:.3e}")

2x2 max error = 0.000e+00
3x3 max error = 3.553e-15
4x4 max error = 1.776e-15
5x5 max error = 3.553e-15
6x6 max error = 3.553e-15
8x8 max error = 5.551e-15
12x12 max error = 3.375e-14
16x16 max error = 1.790e-13
20x20 max error = 7.461e-14
40x40 max error = 1.354e-12
60x60 max error = 1.506e-12
80x80 max error = 6.926e-11
100x100 max error = 5.269e-12
200x200 max error = 7.347e-11
400x400 max error = 7.285e-09
600x600 max error = 5.895e-09
800x800 max error = 1.760e-08
