In [1]:
import numpy as np

In [8]:
def gradient_flow_method(a : np.ndarray, b : np.ndarray, show_annotation : bool = False, eps : float = 10e-12, max_iter = 500) -> tuple:
    if a.shape[0] != a.shape[1]:
        raise ValueError("Matrix a must be square")
    
    if a.shape[0] != b.shape[0]:
        raise ValueError("The dimensions of the two arrays must match")
    
    det_a = np.linalg.det(a)
    if abs(det_a) < 1e-13:
        raise ValueError("Determinant is zero — system has no unique solution")
    
    a = a.copy().astype(float)
    b = b.copy().astype(float)
    n = len(b)
    
    x_k = np.zeros(n)
    x_k1 = np.ones(n)
    k = 0
    if show_annotation:
        print("Step 0")
        print("x_k: ",x_k)
    
    while max(abs(x_k - x_k1)) >= eps and k < max_iter:
        k += 1
        r = b - a @ x_k
        alpha = np.dot(r, r) / np.dot(a @ r, r)
        x_new = x_k + alpha * r
        x_k1 = x_k
        x_k = x_new
        if show_annotation:
            print(f"Step {k}:")
            print(x_k, x_k1, x_k - x_k1)

    if show_annotation:
        print("\nResult: ")
        print(x_k)

    return (x_k, k)

In [7]:
a = np.array([[10, 1, 0, 0, 0], 
              [1, 9, 0, 1, 2], 
              [0, 4, 10, 1, 2], 
              [0, 1, -2, 12, 3], 
              [1, -1, 2, 3, 14]])
b = np.array([11, 13, 17, 14, 19])

x = gradient_flow_method(a, b,show_annotation=True)[0]
b_ = a @ x
max_error = np.max(np.abs(b - b_))
print("\nmax error: ", max_error)

Step 0
x_k:  [0. 0. 0. 0. 0.]
Step 1:
[0.70730741 0.83590876 1.09311145 0.90020943 1.2217128 ] [0. 0. 0. 0. 0.] [0.70730741 0.83590876 1.09311145 0.90020943 1.2217128 ]
Step 2:
[0.98990738 0.96627144 1.0365749  0.98090792 0.96003006] [0.70730741 0.83590876 1.09311145 0.90020943 1.2217128 ] [ 0.28259997  0.13036269 -0.05653655  0.08069849 -0.26168274]
Step 3:
[0.99918298 0.99469873 1.02749575 1.0123118  0.9958547 ] [0.98990738 0.96627144 1.0365749  0.98090792 0.96003006] [ 0.0092756   0.02842729 -0.00907914  0.03140388  0.03582464]
Step 4:
[1.00053177 0.99915489 1.0016869  1.00480134 0.99201232] [0.99918298 0.99469873 1.02749575 1.0123118  0.9958547 ] [ 0.00134879  0.00445616 -0.02580885 -0.00751046 -0.00384238]
Step 5:
[1.00015491 1.00069249 1.00149188 1.00232121 0.99982097] [1.00053177 0.99915489 1.0016869  1.00480134 0.99201232] [-0.00037686  0.0015376  -0.00019503 -0.00248013  0.00780865]
Step 6:
[0.99998525 1.00006048 1.0000045  1.00042708 0.99929848] [1.00015491 1.00069249 1.00149

In [13]:
def return_max_error(a, b):
    x = gradient_flow_method(a, b)
    b_ = a @ x[0]
    max_error = np.max(np.abs(b - b_))
    return max_error, x[1]

a2 = np.array([[4, 2],
               [2, 3]])
b2 = np.array([6, 8])

a3 = np.array([[6, 2, 1],
               [2, 5, 2],
               [1, 2, 4]])
b3 = np.array([9, 10, 7])

a4 = np.array([[10, 2, 3, 1],
               [2, 8, 1, 0],
               [3, 1, 9, 4],
               [1, 0, 4, 7]])
b4 = np.array([12, 9, 11, 8])

a5 = np.array([[9, 1, 2, 3, 1],
               [1, 7, 1, 2, 0],
               [2, 1, 8, 1, 2],
               [3, 2, 1, 10, 3],
               [1, 0, 2, 3, 7]])
b5 = np.array([17, 13, 15, 18, 10])

a6 = np.array([[12, 3, 2, 1, 0, 2],
               [3, 9, 1, 0, 2, 1],
               [2, 1, 11, 4, 1, 2],
               [1, 0, 4, 11, 2, 3],
               [0, 2, 1, 2, 8, 1],
               [2, 1, 2, 3, 1, 10]])
b6 = np.array([15, 12, 18, 14, 10, 16])

systems = [
    (a2, b2),
    (a3, b3),
    (a4, b4),
    (a5, b5),
    (a6, b6)
]

for n in [8, 12, 16, 20, 40, 60, 80, 100, 200, 400, 600, 800]:
    M = np.random.randn(n, n)
    A = M.T @ M
    A += np.eye(n) * n * 0.1
    x_true = np.ones(n)
    b = A @ x_true
    systems.append((A, b))

for a, b in systems:
    err, count = return_max_error(a, b)
    print(f"{a.shape[0]}x{a.shape[0]} max error = {err:.3e}, iterations = {count}")

2x2 max error = 7.761e-12, iterations = 26
3x3 max error = 1.675e-11, iterations = 39
4x4 max error = 4.405e-11, iterations = 48
5x5 max error = 3.498e-11, iterations = 39
6x6 max error = 5.089e-11, iterations = 43
8x8 max error = 7.694e-11, iterations = 227
12x12 max error = 1.954e-10, iterations = 351
16x16 max error = 2.692e-10, iterations = 343
20x20 max error = 4.216e-10, iterations = 449
40x40 max error = 7.774e-10, iterations = 450
60x60 max error = 1.290e-09, iterations = 402
80x80 max error = 1.580e-09, iterations = 401
100x100 max error = 1.966e-09, iterations = 427
200x200 max error = 4.194e-09, iterations = 433
400x400 max error = 8.658e-09, iterations = 441
600x600 max error = 1.189e-08, iterations = 428
800x800 max error = 1.694e-08, iterations = 445
