In [6]:
import numpy as np
import copy

In [16]:
def reflections_method(a: np.ndarray, b:np.ndarray, show_annotation : bool = False) -> np.ndarray:
    if a.shape[0] != a.shape[1]:
        raise ValueError("Matrix a must be square")
    
    if a.shape[0] != b.shape[0]:
        raise ValueError("The dimensions of the two arrays must match")
    
    det_a = np.linalg.det(a)
    if abs(det_a) < 1e-13:
        raise ValueError("Determinant is zero — system has no unique solution")
    
    n = len(b)
    A = a.copy().astype(float)
    f = b.copy().astype(float)
    
    for k in range(n - 1):
        A = copy.deepcopy(A)
        p = np.zeros(n)
        sign = 1 if A[k,k] >= 0 else -1
        p[k] = A[k,k] + sign * np.sqrt(np.sum(A[k:,k] ** 2))
        p[k+1:] = A[k+1:,k]
        
        A[k,k] = -sign * np.sqrt(np.sum(A[k:,k] ** 2))
        denom = np.sum(p[k:] ** 2)
        A[k+1:, k] = 0
        
        for j in range(k+1, n):
            numer = np.dot(p[k:], A[k:,j])
            for i in range(k, n):
                A[i,j] -= 2 * p[i] * (numer / denom)
               
                
        f_numer = np.dot(p[k:], f[k:])
        for i in range(k, n):
            f[i] -= 2 * p[i] * f_numer  / denom
            
        if show_annotation:
            print(f"\nStep {k+1}")
            print("p =", p)
            print("A =", A)
            print("f =", f)
        
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (f[i] - np.dot(A[i, i+1:], x[i+1:])) / A[i, i]
    
    return x

In [21]:
a = np.array([[1, 3, -2, 0, -2], 
              [3, 4, -5, 1, -3], 
              [-2, -5, 3, -2, 2], 
              [0, 1, -2, 5, 3], 
              [-2, -3, 2, 3, 4]])
b = np.array([0.5, 5.4, 5, 7.5, 3.3])

x = reflections_method(a, b, show_annotation=True)
print(x)
b_ = a @ x
max_error = np.max(np.abs(b - b_))
print("max error: ", max_error)


Step 1
p = [ 5.24264069  3.         -2.          0.         -2.        ]
A = [[-4.24264069 -7.30677007  6.36396103 -0.23570226  5.42115199]
 [ 0.         -1.89785035 -0.21388465  0.86512393  1.24661107]
 [ 0.         -1.06809977 -0.19074357 -1.91008262 -0.83107405]
 [ 0.          1.         -2.          5.          3.        ]
 [ 0.          0.93190023 -1.19074357  3.08991738  1.16892595]]
f = [-0.02357023  5.10039704  5.19973531  7.5         3.49973531]

Step 2
p = [ 0.         -4.46905845 -1.06809977  1.          0.93190023]
A = [[-4.24264069 -7.30677007  6.36396103 -0.23570226  5.42115199]
 [ 0.          2.5712081  -0.97230559  3.21941183  1.01551917]
 [ 0.          0.         -0.37200529 -1.34741055 -0.88630474]
 [ 0.          0.         -1.83029514  4.47320271  3.0517093 ]
 [ 0.          0.         -1.03259557  2.59899486  1.21711387]]
f = [-0.02357023 -1.73934666  3.56504453  9.03046638  4.92597728]

Step 3
p = [ 0.          0.         -2.5061613  -1.83029514 -1.03259557]
A = [[

In [18]:
def return_max_error(a, b):
    x = reflections_method(a, b)
    b_ = a @ x
    max_error = np.max(np.abs(b - b_))
    return max_error


a2 = np.array([[4, 2],
               [2, 3]])
b2 = np.array([6, 8])

a3 = np.array([[6, 2, 1],
               [2, 5, 2],
               [1, 2, 4]])
b3 = np.array([9, 10, 7])

a4 = np.array([[10, 2, 3, 1],
               [2, 8, 1, 0],
               [3, 1, 9, 4],
               [1, 0, 4, 7]])
b4 = np.array([12, 9, 11, 8])

a5 = np.array([[9, 1, 2, 3, 1],
               [1, 7, 1, 2, 0],
               [2, 1, 8, 1, 2],
               [3, 2, 1, 10, 3],
               [1, 0, 2, 3, 6]])
b5 = np.array([17, 13, 15, 18, 10])

a6 = np.array([[12, 3, 2, 1, 0, 2],
               [3, 9, 1, 0, 2, 1],
               [2, 1, 11, 4, 1, 2],
               [1, 0, 4, 10, 2, 3],
               [0, 2, 1, 2, 8, 1],
               [2, 1, 2, 3, 1, 9]])
b6 = np.array([15, 12, 18, 14, 10, 16])

systems = [
    (a2, b2),
    (a3, b3),
    (a4, b4),
    (a5, b5),
    (a6, b6)
]

for n in [8, 12, 16, 20, 40, 60, 80, 100, 200, 400, 600]:
    A = np.random.randn(n, n)
    x_true = np.ones(n)
    b = A @ x_true
    systems.append((A, b))

for a, b in systems:
    err = return_max_error(a, b)
    print(f"{a.shape[0]}x{a.shape[0]} max error = {err:.3e}")

2x2 max error = 0.000e+00
3x3 max error = 1.776e-15
4x4 max error = 0.000e+00
5x5 max error = 5.329e-15
6x6 max error = 3.553e-15
8x8 max error = 5.329e-15
12x12 max error = 2.665e-15
16x16 max error = 3.553e-15
20x20 max error = 4.441e-15
40x40 max error = 7.105e-15
60x60 max error = 1.066e-14
80x80 max error = 1.510e-14
100x100 max error = 1.865e-14
200x200 max error = 3.375e-14
400x400 max error = 7.105e-14
600x600 max error = 8.704e-14
