In [1]:
import numpy as np
import pandas as pd

In [9]:
def relaxation_method(a : np.ndarray, b : np.ndarray, w : float = 1, show_annotation : bool = False, eps : float = 10e-8) -> tuple:
    if a.shape[0] != a.shape[1]:
        raise ValueError("Matrix a must be square")
    
    if a.shape[0] != b.shape[0]:
        raise ValueError("The dimensions of the two arrays must match")
    
    det_a = np.linalg.det(a)
    if abs(det_a) < 1e-13:
        raise ValueError("Determinant is zero — system has no unique solution")
    
    a = a.copy().astype(float)
    b = b.copy().astype(float)
    n = len(b)
    
    for i in range(n):
        if abs(a[i, i]) <= np.sum(np.abs(a[i])) - abs(a[i, i]):
            raise ValueError("Matrix should have diagonal dominance")
    
    x_k = np.zeros(n)
    x_k1 = np.ones(n)
    k = 0
    if show_annotation:
        print("Step 0")
        print("x_k: ",x_k)
    
    while max(abs(x_k - x_k1)) >= eps:
        x_new = x_k * (1 - w)
        k += 1
        for i in range(n):
            x_new[i] += (w / a[i,i]) * (b[i] - np.sum([a[i,j] * x_new[j] for j in range(i)]) - np.sum([a[i,j] * x_k[j] for j in range(i + 1, n)]))
        x_k1 = x_k
        x_k = x_new
        if show_annotation:
            print(f"Step {k}:")
            print(x_k1, x_k, x_k - x_k1)

    if show_annotation:
        print("\nResult: ")
        print(x_k)

    return (x_k, k)

In [10]:
a = np.array([[15.21,0, 1.11], 
              [1.32,14.82,-0.61], 
              [0.75,-1.26,-15.44]])
b = np.array([9.01,8.52,8.33])

x = relaxation_method(a, b, 1,show_annotation=True, eps=0.0001)[0]
b_ = a @ x
max_error = np.max(np.abs(b - b_))
print("\nmax error: ", max_error)

Step 0
x_k:  [0. 0. 0.]
Step 1:
[0. 0. 0.] [ 0.59237344  0.52213678 -0.55334276] [ 0.59237344  0.52213678 -0.55334276]
Step 2:
[ 0.59237344  0.52213678 -0.55334276] [ 0.63275545  0.49576408 -0.54922903] [ 0.04038202 -0.0263727   0.00411374]
Step 3:
[ 0.63275545  0.49576408 -0.54922903] [ 0.63245524  0.49596015 -0.54925961] [-3.00213592e-04  1.96063554e-04 -3.05829192e-05]
Step 4:
[ 0.63245524  0.49596015 -0.54925961] [ 0.63245747  0.49595869 -0.54925938] [ 2.23188957e-06 -1.45760290e-06  2.27363784e-07]

Result: 
[ 0.63245747  0.49595869 -0.54925938]

max error:  2.5237380008036325e-07


## Попробуем для других w

In [11]:
a = np.array([[15.21,0, 1.11], 
              [1.32,14.82,-0.61], 
              [0.75,-1.26,-15.44]])
b = np.array([9.01,8.52,8.33])

x = relaxation_method(a, b, 0.5,show_annotation=True, eps=0.0001)[0]
b_ = a @ x
max_error = np.max(np.abs(b - b_))
print("\nmax error: ", max_error)

Step 0
x_k:  [0. 0. 0.]
Step 1:
[0. 0. 0.] [ 0.29618672  0.27425889 -0.27375085] [ 0.29618672  0.27425889 -0.27375085]
Step 2:
[ 0.29618672  0.27425889 -0.27375085] [ 0.45426902  0.39871436 -0.41186501] [ 0.1580823   0.12445547 -0.13811416]
Step 3:
[ 0.45426902  0.39871436 -0.41186501] [ 0.53834983  0.45435518 -0.48115029] [ 0.08408082  0.05564081 -0.06928528]
Step 4:
[ 0.53834983  0.45435518 -0.48115029] [ 0.5829184   0.47876484 -0.51570645] [ 0.04456857  0.02440966 -0.03455617]
Step 5:
[ 0.5829184   0.47876484 -0.51570645] [ 0.60646361  0.48920992 -0.53283887] [ 0.02354521  0.01044508 -0.01713242]
Step 6:
[ 0.60646361  0.48920992 -0.53283887] [ 0.61886136  0.49352774 -0.54128015] [ 0.01239775  0.00431782 -0.00844128]
Step 7:
[ 0.61886136  0.49352774 -0.54128015] [ 0.62536825  0.49522315 -0.54541194] [ 0.00650689  0.00169541 -0.00413178]
Step 8:
[ 0.62536825  0.49522315 -0.54541194] [ 0.62877247  0.49583422 -0.54742008] [ 0.00340421  0.00061107 -0.00200814]
Step 9:
[ 0.62877247  0.495

In [12]:
a = np.array([[15.21,0, 1.11], 
              [1.32,14.82,-0.61], 
              [0.75,-1.26,-15.44]])
b = np.array([9.01,8.52,8.33])

x = relaxation_method(a, b, 1.5,show_annotation=True, eps=0.0001)[0]
b_ = a @ x
max_error = np.max(np.abs(b - b_))
print("\nmax error: ", max_error)

Step 0
x_k:  [0. 0. 0.]
Step 1:
[0. 0. 0.] [ 0.88856016  0.74363366 -0.83554647] [ 0.88856016  0.74363366 -0.83554647]
Step 2:
[ 0.88856016  0.74363366 -0.83554647] [ 0.53574522  0.36736667 -0.39742169] [-0.35281493 -0.376267    0.43812478]
Step 3:
[ 0.53574522  0.36736667 -0.39742169] [ 0.66419229  0.56538944 -0.63136491] [ 0.12844706  0.19802277 -0.23394322]
Step 4:
[ 0.66419229  0.56538944 -0.63136491] [ 0.62557793  0.45709319 -0.50395038] [-0.03861436 -0.10829624  0.12741454]
Step 5:
[ 0.62557793  0.45709319 -0.50395038] [ 0.63093736  0.51839196 -0.57477068] [ 0.00535944  0.06129877 -0.07082031]
Step 6:
[ 0.63093736  0.51839196 -0.57477068] [ 0.63601016  0.48269233 -0.53462094] [ 0.0050728  -0.03569964  0.04014974]
Step 7:
[ 0.63601016  0.48269233 -0.53462094] [ 0.62907867  0.50394709 -0.55780264] [-0.00693149  0.02125477 -0.0231817 ]
Step 8:
[ 0.62907867  0.50394709 -0.55780264] [ 0.63508206  0.49108638 -0.5442001 ] [ 0.00600339 -0.01286071  0.01360254]
Step 9:
[ 0.63508206  0.491

In [6]:
def return_max_error(a, b):
    x = relaxation_method(a, b, 1)
    b_ = a @ x[0]
    max_error = np.max(np.abs(b - b_))
    x2 = relaxation_method(a, b, 0.5)
    max_error2 = np.max(np.abs(b - b_))
    x3 = relaxation_method(a, b, 1.5)
    max_error3 = np.max(np.abs(b - b_))
    return max_error, x[1], max_error2, x2[1], max_error3, x3[1]

a2 = np.array([[4, 2],
               [2, 3]])
b2 = np.array([6, 8])

a3 = np.array([[6, 2, 1],
               [2, 5, 2],
               [1, 2, 4]])
b3 = np.array([9, 10, 7])

a4 = np.array([[10, 2, 3, 1],
               [2, 8, 1, 0],
               [3, 1, 9, 4],
               [1, 0, 4, 7]])
b4 = np.array([12, 9, 11, 8])

a5 = np.array([[9, 1, 2, 3, 1],
               [1, 7, 1, 2, 0],
               [2, 1, 8, 1, 2],
               [3, 2, 1, 10, 3],
               [1, 0, 2, 3, 7]])
b5 = np.array([17, 13, 15, 18, 10])

a6 = np.array([[12, 3, 2, 1, 0, 2],
               [3, 9, 1, 0, 2, 1],
               [2, 1, 11, 4, 1, 2],
               [1, 0, 4, 11, 2, 3],
               [0, 2, 1, 2, 8, 1],
               [2, 1, 2, 3, 1, 10]])
b6 = np.array([15, 12, 18, 14, 10, 16])

systems = [
    (a2, b2),
    (a3, b3),
    (a4, b4),
    (a5, b5),
    (a6, b6)
]

for n in [8, 12, 16, 20, 40, 60, 80, 100, 200, 400, 600, 800]:
    A = np.random.randn(n, n)
    A = abs(A) + np.eye(n) * np.sum(abs(A), axis=1) * 1.5
    x_true = np.ones(n)
    b = A @ x_true
    systems.append((A, b))
results = []
for a, b in systems:
    (err1, it1,
    err2, it2, 
     err3, it3) = return_max_error(a, b)

    results.append({
        "Размер": a.shape[0],
        "w=1 ошибка": err1,
        "w=1 итерации": it1,
        "w=0.5 ошибка": err2,
        "w=0.5 итерации": it2,
        "w=1.5 ошибка": err3,
        "w=1.5 итерации": it3,
    })

df = pd.DataFrame(results)
df

D:\matstat\lab1\venv\Lib\site-packages\numpy\linalg\_linalg.py:2383: RuntimeWarning: overflow encountered in det
  r = _umath_linalg.det(a, signature=signature)


Размер    w=1 ошибка  w=1 итерации  w=0.5 ошибка  w=0.5 итерации  \
0        2  4.181503e-07            31  4.181503e-07             101   
1        3  5.957995e-07            20  5.957995e-07              84   
2        4  1.735333e-07            27  1.735333e-07              93   
3        5  9.276552e-08            24  9.276552e-08              80   
4        6  1.438146e-07            21  1.438146e-07              67   
5        8  3.552714e-15            15  3.552714e-15              59   
6       12  3.552714e-15            17  3.552714e-15              49   
7       16  7.105427e-15            17  7.105427e-15              51   
8       20  1.421085e-14            17  1.421085e-14              49   
9       40  2.842171e-14            19  2.842171e-14              49   
10      60  5.684342e-14            17  5.684342e-14              47   
11      80  5.684342e-14            19  5.684342e-14              47   
12     100  8.526513e-14            19  8.526513e-14              47   
13     200  2.842171e-13            19  2.842171e-13              47   
14     400  6.821210e-13            19  6.821210e-13              47   
15     600  1.136868e-12            19  1.136868e-12              47   
16     800  2.728484e-12            19  2.728484e-12              47   

    w=1.5 ошибка  w=1.5 итерации  
0   4.181503e-07              48  
1   5.957995e-07              54  
2   1.735333e-07              51  
3   9.276552e-08              56  
4   1.438146e-07              57  
5   3.552714e-15              55  
6   3.552714e-15              69  
7   7.105427e-15              65  
8   1.421085e-14              59  
9   2.842171e-14              67  
10  5.684342e-14              61  
11  5.684342e-14              63  
12  8.526513e-14              65  
13  2.842171e-13              63  
14  6.821210e-13              63  
15  1.136868e-12              63  
16  2.728484e-12              63