In [1]:
import numpy as np

In [2]:
def simple_iteration_method(a : np.ndarray, f : np.ndarray, show_annotation : bool = False, eps : float = 10e-12) -> tuple:
    if a.shape[0] != a.shape[1]:
        raise ValueError("Matrix a must be square")
    
    if a.shape[0] != f.shape[0]:
        raise ValueError("The dimensions of the two arrays must match")
    
    det_a = np.linalg.det(a)
    if abs(det_a) < 1e-13:
        raise ValueError("Determinant is zero — system has no unique solution")
    
    a = a.copy().astype(float)
    f = f.copy().astype(float)
    n = len(f)
    
    for i in range(n):
        if abs(a[i, i]) <= np.sum(np.abs(a[i])) - abs(a[i, i]):
            raise ValueError("Matrix should have diagonal dominance")
    
    x_k = np.zeros(n)
    x_k1 = np.ones(n)
    k = 0
    
    while max(abs(x_k - x_k1)) >= eps:
        x_new = np.zeros(n)
        k += 1
        for i in range(n):
            x_new[i] = (f[i] - np.sum([a[i,j] * x_k[j] if j != i else 0 for j in range(n)])) / a [i,i]
        x_k = x_k1
        x_k1 = x_new
        if show_annotation:
            print(f"Step {k}:")
            print(x_k, x_k1, x_k - x_k1)
    
    if show_annotation:
        print("Result:")
        print(x_k1)
    
    return (x_k1, k)


In [3]:
a = np.array([[10, 1, 0, 0, 0], 
              [1, 9, 0, 1, 2], 
              [0, 4, 10, 1, 2], 
              [0, 1, -2, 12, 3], 
              [1, -1, 2, 3, 14]])
b = np.array([11, 13, 17, 14, 19])

x = simple_iteration_method(a, b, show_annotation=True)[0]
b_ = a @ x
max_error = np.max(np.abs(b - b_))
print("max error: ", max_error)

Step 1:
[1. 1. 1. 1. 1.] [1.1        1.44444444 1.7        1.16666667 1.35714286] [-0.1        -0.44444444 -0.7        -0.16666667 -0.35714286]
Step 2:
[1.1        1.44444444 1.7        1.16666667 1.35714286] [1. 1. 1. 1. 1.] [0.1        0.44444444 0.7        0.16666667 0.35714286]
Step 3:
[1. 1. 1. 1. 1.] [0.95555556 0.89100529 0.73412698 0.99034392 0.88888889] [0.04444444 0.10899471 0.26587302 0.00965608 0.11111111]
Step 4:
[0.95555556 0.89100529 0.73412698 0.99034392 0.88888889] [1. 1. 1. 1. 1.] [-0.04444444 -0.10899471 -0.26587302 -0.00965608 -0.11111111]
Step 5:
[1. 1. 1. 1. 1.] [1.01089947 1.03070253 1.06678571 0.9925485  1.03544029] [-0.01089947 -0.03070253 -0.06678571  0.0074515  -0.03544029]
Step 6:
[1.01089947 1.03070253 1.06678571 0.9925485  1.03544029] [1. 1. 1. 1. 1.] [ 0.01089947  0.03070253  0.06678571 -0.0074515   0.03544029]
Step 7:
[1. 1. 1. 1. 1.] [0.99692975 0.99174127 0.98137608 0.99971234 0.99347044] [0.00307025 0.00825873 0.01862392 0.00028766 0.00652956]
Step 8:

In [81]:
def return_max_error(a, b):
    x = simple_iteration_method(a, b)
    b_ = a @ x[0]
    max_error = np.max(np.abs(b - b_))
    return max_error, x[1]


a2 = np.array([[4, 2],
               [2, 3]])
b2 = np.array([6, 8])

a3 = np.array([[6, 2, 1],
               [2, 5, 2],
               [1, 2, 4]])
b3 = np.array([9, 10, 7])

a4 = np.array([[10, 2, 3, 1],
               [2, 8, 1, 0],
               [3, 1, 9, 4],
               [1, 0, 4, 7]])
b4 = np.array([12, 9, 11, 8])

a5 = np.array([[9, 1, 2, 3, 1],
               [1, 7, 1, 2, 0],
               [2, 1, 8, 1, 2],
               [3, 2, 1, 10, 3],
               [1, 0, 2, 3, 7]])
b5 = np.array([17, 13, 15, 18, 10])

a6 = np.array([[12, 3, 2, 1, 0, 2],
               [3, 9, 1, 0, 2, 1],
               [2, 1, 11, 4, 1, 2],
               [1, 0, 4, 11, 2, 3],
               [0, 2, 1, 2, 8, 1],
               [2, 1, 2, 3, 1, 10]])
b6 = np.array([15, 12, 18, 14, 10, 16])

systems = [
    (a2, b2),
    (a3, b3),
    (a4, b4),
    (a5, b5),
    (a6, b6)
]

for n in [8, 12, 16, 20, 40, 60, 80, 100, 200, 400, 600, 800]:
    A = np.random.randn(n, n)
    A = abs(A) + np.eye(n) * np.sum(abs(A), axis=1) * 2
    x_true = np.ones(n)
    b = A @ x_true
    systems.append((A, b))

for a, b in systems:
    err, count = return_max_error(a, b)
    print(f"{a.shape[0]}x{a.shape[0]} max error = {err:.3e}, iterations = {count}")

2x2 max error = 6.295e-12, iterations = 101
3x3 max error = 7.020e-11, iterations = 148
4x4 max error = 1.172e-10, iterations = 158
5x5 max error = 1.520e-10, iterations = 246
6x6 max error = 8.402e-12, iterations = 307
8x8 max error = 1.346e-10, iterations = 70
12x12 max error = 1.594e-10, iterations = 72
16x16 max error = 2.884e-10, iterations = 72
20x20 max error = 3.812e-10, iterations = 78
40x40 max error = 5.556e-12, iterations = 83
60x60 max error = 1.528e-09, iterations = 84
80x80 max error = 2.247e-09, iterations = 86
100x100 max error = 2.001e-09, iterations = 88
200x200 max error = 5.224e-09, iterations = 90
400x400 max error = 6.176e-09, iterations = 94
600x600 max error = 1.450e-08, iterations = 94
800x800 max error = 1.294e-08, iterations = 96


## А если сделать диагональное преобладание слабее, то будет гораздо больше итераций

In [82]:
systems2 = []
for n in [8, 12, 16, 20, 40, 60, 80, 100, 200, 400, 600, 800]:
    A = np.random.randn(n, n)
    A = abs(A) + np.eye(n) * np.sum(abs(A), axis=1)
    x_true = np.ones(n)
    b = A @ x_true
    systems2.append((A, b))

for a, b in systems2:
    err, count = return_max_error(a, b)
    print(f"{a.shape[0]}x{a.shape[0]} max error = {err:.3e}, iterations = {count}")

8x8 max error = 1.171e-11, iterations = 495
12x12 max error = 1.089e-11, iterations = 279
16x16 max error = 2.906e-10, iterations = 414
20x20 max error = 3.645e-10, iterations = 506
40x40 max error = 1.172e-11, iterations = 1467
60x60 max error = 1.123e-11, iterations = 1783
80x80 max error = 1.137e-11, iterations = 2145
100x100 max error = 1.752e-09, iterations = 2870


KeyboardInterrupt: 

## Если преобладание сильное, то очень быстро находится

In [85]:
systems3 = []
for n in [8, 12, 16, 20, 40, 60, 80, 100, 200, 400, 600, 800]:
    A = np.random.randn(n, n)
    A = abs(A) + np.eye(n) * np.sum(abs(A), axis=1) * 100
    x_true = np.ones(n)
    b = A @ x_true
    systems3.append((A, b))

for a, b in systems3:
    err, count = return_max_error(a, b)
    print(f"{a.shape[0]}x{a.shape[0]} max error = {err:.3e}, iterations = {count}")

8x8 max error = 1.058e-09, iterations = 14
12x12 max error = 8.328e-09, iterations = 14
16x16 max error = 1.485e-08, iterations = 14
20x20 max error = 2.801e-10, iterations = 16
40x40 max error = 1.054e-09, iterations = 16
60x60 max error = 2.701e-09, iterations = 16
80x80 max error = 4.626e-09, iterations = 16
100x100 max error = 7.161e-09, iterations = 16
200x200 max error = 3.147e-08, iterations = 16
400x400 max error = 1.134e-07, iterations = 16
600x600 max error = 2.526e-07, iterations = 16
800x800 max error = 4.568e-07, iterations = 16
